package at.robthered.plan_me.features.update_hashtag_name_dialog.presentation.navigation

import at.robthered.plan_me.features.common.presentation.navigation.BaseNavigationEventDispatcher

class UpdateHashtagNameDialogNavigationEventDispatcherImpl :
    BaseNavigationEventDispatcher<UpdateHashtagNameDialogNavigationEvent>(),
    UpdateHashtagNameDialogNavigationEventDispatcher