package at.robthered.plan_me.features.task_hashtags_dialog.presentation.navigation

import at.robthered.plan_me.features.common.presentation.navigation.NavigationEventDispatcher

interface TaskHashtagsDialogNavigationDispatcher
    : NavigationEventDispatcher<TaskHashtagsDialogNavigationEvent>