package at.robthered.plan_me.features.task_statistics_dialog.presentation.navigation

import at.robthered.plan_me.features.common.presentation.navigation.NavigationEventDispatcher

interface TaskStatisticsDialogNavigationEventDispatcher :
    NavigationEventDispatcher<TaskStatisticsDialogNavigationEvent>