package at.robthered.plan_me.features.common.domain

enum class RoomDatabaseError : LocalDatabaseError {
    DISK_IO_ERROR,
    CONSTRAINT_VIOLATION,
    CORRUPT_DATABASE,
    CANT_OPEN,
    ILLEGAL_STATE,
    UNKNOWN,
    NO_TASK_FOUND,
    NO_HASHTAG_FOUND,
    NO_SECTION_FOUND,
    NO_TASK_ARCHIVED_HISTORY_FOUND,
    NO_TASK_COMPLETED_HISTORY_FOUND,
    NO_TASK_DESCRIPTION_HISTORY_FOUND,
    NO_TASK_PRIORITY_HISTORY_FOUND,
    NO_TASK_TITLE_HISTORY_FOUND,
    NO_TASK_HASHTAG_CROSS_REF_FOUND,
    NO_TASK_SCHEDULE_EVENT_FOUND,
}