package at.robthered.plan_me.features.update_task_dialog.presentation.navigation

import at.robthered.plan_me.features.common.presentation.navigation.NavigationEventDispatcher

interface UpdateTaskDialogNavigationEventDispatcher :
    NavigationEventDispatcher<UpdateTaskDialogNavigationEvent>