package at.robthered.plan_me.features.hashtag_tasks_dialog.presentation.navigation

import at.robthered.plan_me.features.common.presentation.navigation.NavigationEventDispatcher

interface HashtagTasksDialogNavigationEventDispatcher :
    NavigationEventDispatcher<HashtagTasksDialogNavigationEvent>