package at.robthered.plan_me.features.task_details_dialog.presentation.navigation

import at.robthered.plan_me.features.common.presentation.navigation.NavigationEventDispatcher

interface TaskDetailsDialogNavigationEventDispatcher :
    NavigationEventDispatcher<TaskDetailsDialogNavigationEvent>