package at.robthered.plan_me.features.priority_picker_dialog.presentation.navigation

import at.robthered.plan_me.features.common.presentation.navigation.NavigationEventDispatcher

interface PriorityPickerDialogNavigationEventDispatcher :
    NavigationEventDispatcher<PriorityPickerDialogNavigationEvent>